### ISSUE TITLE
게시글 작성 시 키보드가 내려가지 않는 문제

### ISSUE THREAD

**Issue by yooxdb** [wafflestudio19-5/team9-iOS#15]
지금은 View만 우선 짜두신 것 같은데 추후 게시글 작성 중에 키보드를 내릴 수 있는 방법에 대한 구현도 부탁드립니다! 실제 앱에서는 `panGesture`을 이용하고 있으니 이 방식대로 구현하시면 될 것 같습니다.

_Originally posted by @peng-u-0807 in https://github.com/wafflestudio19-5/team9-iOS/pull/12#discussion_r770223854_

**Comment by shp7724** [comment]
#30 에서 수정했습니다.
