### ISSUE TITLE
[Bug] 이모지 인식 안됨

### ISSUE THREAD

**Issue by yabsed** [wafflestudio19-5/team9-iOS#39]
![image](https://user-images.githubusercontent.com/14042027/148643962-977c5ec1-207e-4fd1-b4bf-c9a7f8304dbc.png)
이모지를 입력하려고 시도하면 ???이 뜹니다

**Comment by IHIHHIHI** [comment]
https://lee-seul.github.io/django/backend/2018/01/07/emoji-insert-into-mysql.html
