### ISSUE TITLE
스크롤뷰에서 tapGesture 사용시 고려해야 할 문제

### ISSUE THREAD

**Issue by shp7724** [wafflestudio19-5/team9-iOS#49]
***스크롤뷰에 속한*** 뷰에 대해서 터치 제스쳐를 등록할 때 

```swift
view.rx.tapGesture()
            .when(.recognized)
            .bind { [weak self] _ in }
            .disposed(by: cell.refreshingBag)
```

단순히 위와 같이 사용하면 스크롤뷰의 gestureRecognizer와 RxGesture에 의해 등록된 gestureRecognizer가 동시에 작동해서
스크롤할때 원치 않게 제스쳐가 인식되는 경우가 있습니다. 

#48 에서 추가된 `TapGestureConfigurations.scrollViewTapConfig`를 사용하시면 해당 문제를 방지할 수 있습니다.

```swift
view.rx.tapGesture(configuration: TapGestureConfigurations.scrollViewTapConfig)
            .when(.recognized)
            .bind { [weak self] _ in }
            .disposed(by: cell.refreshingBag)
```

@KWSMooBang @peng-u-0807 두분 다 확인하시면 Close하겠습니다!

**Comment by yooxdb** [comment]
@shp7724 확인했습니다 좋은 정보 감사합니다👍
