### ISSUE TITLE
BottomSheetView가 올라온 경우 cell을 선택하기 전까진 내려가지 않는 문제

### ISSUE THREAD

**Issue by yooxdb** [wafflestudio19-5/team9-iOS#66]
![image](https://user-images.githubusercontent.com/70614553/151023084-71bbcac3-0ab5-4a51-9e5d-dbcf394f7d29.png)
메뉴를 선택하지 않고도 회색 공간을 누르면 bottomSheet가 내려가야될 것 같은데 내려가지 않는 문제가 있습니다.

**Comment by shp7724** [comment]
여기에 덧붙여서 BottomSheet가 올라올 때 화면이 어두워지는 애니메이션이 뭔가 부자연스럽습니다.. 저도 한번 고쳐보려고 시도해봤는데 잘 안되네요.

**Comment by yooxdb** [comment]
이게 BottomSheet 뷰컨을 띄우는 방식이 아니라...뷰를 띄우는 방식으로 수정해야될 것 같네요

**Comment by shp7724** [comment]
재사용성의 측면에서는 ViewController로 접근하는 게 맞을 것 같긴 합니다.

iOS15부터 `UISheetPresentationController`가 생겼는데 이걸 사용해봐도 좋을 것 같아요. 

https://sarunw.com/posts/bottom-sheet-in-ios-15-with-uisheetpresentationcontroller/

**Comment by KWSMooBang** [comment]
말씀해주신 부분들 반영해서 수정해보겠습니다.
